apiVersion: v1 
kind: ConfigMap
metadata:
  name: display 
data:
  DISPLAY: x-server:1
---
apiVersion: v1 
kind: Pod 
metadata:
  name: vnc 
  labels:
    app: vnc 
spec: 
  containers:
  - image: ghcr.io/rutgerhartog/geryon:vnc 
    name: vnc 
    envFrom:
    - configMapRef:
        name: display  
    command:
    - x11vnc 
    args:
    - "-display" 
    - "x-server:1" 
    - "-xkb" 
    - "-rfbport" 
    - "5901"
    - "-noshm" 
    - "-noxrecord" 
    - "-noxfixes"
    - "-noxdamage"
    - "-forever"
    - "-nopw"
---
apiVersion: v1 
kind: Service 
metadata:
  name: vnc 
spec: 
  selector:
    app: vnc 
  ports:
  - protocol: TCP 
    port: 5901
---
apiVersion: v1 
kind: Pod 
metadata:
  name: x-server 
  labels:
    app: x-server 
spec: 
  containers:
  - image: ghcr.io/rutgerhartog/geryon:x-server 
    name: x-server
    command:
    - Xvfb
    args:
    - :1
    - -ac 
    - -listen 
    - tcp
---
apiVersion: v1 
kind: Service 
metadata:
  name: x-server 
spec: 
  selector:
    app: x-server 
  ports:
  - protocol: TCP 
    port: 6001

# ---
# apiVersion: v1 
# kind: Pod
# metadata:
#   name: window-manager
# spec: 
#   containers:
#   - image: ghcr.io/rutgerhartog/geryon:wm 
#     name: wm 
#     envFrom:
#     - configMapRef:
#         name: display
