apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: apptemplates.apps.local
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: apps.local
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image: 
                  type: string
                env: 
                  type: array
                  items:
                    type: object
                    properties:
                      name: 
                        type: string 
                      value: 
                        type: string 
                labels:
                  type: object 
                data:
                  type: array 
                  items:
                    type: string 
                sa: 
                  type: bool 

  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: apptemplates
    # singular name to be used as an alias on the CLI and for display
    singular: apptemplate
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AppTemplate
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - apptemplate
    - apptemp
    - at