name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '32 21 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
        with:
          cosign-release: 'v1.7.1'

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base 
        id: build-base
        uses: docker/build-push-action@v3 
        with:
          context: apps/images/base/
          push: ${{ github.event_name != 'pull_request' }} 
          tags: ghcr.io/rutgerhartog/geryon:base


      - name: Build and push VNC 
        id: build-vnc
        uses: docker/build-push-action@v3 
        with:
          context: apps/images/vnc/
          push: ${{ github.event_name != 'pull_request' }} 
          tags: ghcr.io/rutgerhartog/geryon:vnc


      - name: Build and push X server 
        id: build-x-server
        uses: docker/build-push-action@v3 
        with:
          context: apps/images/x-server/
          push: ${{ github.event_name != 'pull_request' }} 
          tags: ghcr.io/rutgerhartog/geryon:x-server

      - name: Sign the published base image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/rutgerhartog/geryon:base@${{ steps.build-base.outputs.digest }}

      - name: Sign the published VNC image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/rutgerhartog/geryon:vnc@${{ steps.build-vnc.outputs.digest }}

      - name: Sign the published X server image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/rutgerhartog/geryon:x-server@${{ steps.build-x-server.outputs.digest }}
